### ISSUE TITLE
chat.openai.com

### ISSUE THREAD

**Issue by Bush2021** [fishjar/kiss-rules#10]
用户发送的内容无法正常翻译；之前是可以翻译的，但是无法换行；我刚刚试了下，完全翻译不了了。

![2023-10-13_155506](https://github.com/fishjar/kiss-rules/assets/79072750/8d6127d7-2495-44cf-83a7-47da0cb56933)

Selector 完整内容：
`#__next > div.relative.z-0.flex.h-full.w-full.overflow-hidden > div.relative.flex.h-full.max-w-full.flex-1.flex-col.overflow-hidden > main > div.flex.h-full.flex-col > div.flex-1.overflow-hidden > div > div > div > div.group.w-full.text-token-text-primary.border-b.border-black\/10.gizmo\:border-0.dark\:border-gray-900\/50.gizmo\:dark\:border-0.gizmo\:bg-transparent.dark\:bg-gray-800.gizmo\:dark\:bg-transparent > div > div > div.relative.flex.w-\[calc\(100\%-50px\)\].flex-col.gizmo\:w-full.lg\:w-\[calc\(100\%-115px\)\].gizmo\:text-gizmo-gray-600.gizmo\:dark\:text-gray-300 > div > div.flex.flex-grow.flex-col.gap-3.max-w-full > div > div`

另外，现有规则会导致刷新进入 https://chat.openai.com/ 时无法发送任何内容，必须手动点击 New Chat 才行。

**Comment by fishjar** [comment]
1、刚进入无法发送内容的原因是之前你提交的`webfix`引起的，你试试取消注入修复补丁。
2、直接复制的selector不是一个好做法，太长了，而且不一定有效。
3、无法换行可能需要另外找办法解决，我看openai直接用`\n`换行，而不是用换行元素包裹。
4、我的openai帐号失效，没法测试，你可以试试这个selector：

```css
div[data-testid^=conversation-turn] .items-start :is(div, li, p, h1, h2, h3, h4, h5, h6, dd, blockquote)
```

**Comment by fishjar** [comment]
我新增加了一类`webfix`，专门针对需要将`\n`转换为`<p>`的情况，将在下个版本发布。
