### ISSUE TITLE
forum.ru-board.com 规则编写求助

### ISSUE THREAD

**Issue by benzBrake** [fishjar/kiss-rules#12]
### 问题说明
默认编写规则，这个网站啥也翻译不出来。

我尝试写了一下规则
```
table[cellpadding] a; .tpc; .post
```

现在`.post`下的`#text`部分文本节点不会被翻译
### 复现页面
http://forum.ru-board.com/topic.cgi?forum=5&topic=51202
### 附加说明
![部分文本节点](https://github.com/fishjar/kiss-rules/assets/11323774/2d843036-f2fc-45bf-a2f7-2156768d24f3)

**Comment by fishjar** [comment]
`补丁设置`那里开启`注入修复补丁`，然后用默认规则即可翻译。

![Screenshot from 2023-11-22 16-58-41](https://github.com/fishjar/kiss-rules/assets/1157624/67d04545-35b2-4daa-8f73-a91ea70b9cfa)
