### ISSUE TITLE
右键菜单的选项消失了

### ISSUE THREAD

**Issue by C1oudTree** [fishjar/kiss-rules#18]
在我使用chrome篡改猴5.0.0时,当我将"基本设置->隐藏悬浮按钮"设置为隐藏时,右键菜单(GM_registerMenuCommand)中的四个设置选项也消失了,我只是不想要悬浮按钮

**Comment by fishjar** [comment]
这是一个bug，需要修复

**Comment by fishjar** [comment]
新版已修复
