### ISSUE TITLE
如何翻译steam的详情页面

### ISSUE THREAD

**Issue by C1oudTree** [fishjar/kiss-rules#19]
默认规则无法翻译.game_area_description 的正文部分,
![image](https://github.com/fishjar/kiss-rules/assets/90253489/3f3f50b4-085a-465e-a76a-d3e26b80305e)

当我使用.game_area_description规则来匹配时,却会把所有翻译的内容不分段的放在结尾,
![image](https://github.com/fishjar/kiss-rules/assets/90253489/5afa9557-e85d-4822-bba5-51403d33cea5)

应该如何正确翻译steam的商店页面

网址:https://store.steampowered.com/app/264710
浏览器:chrome 版本 120.0.6099.110（正式版本） （64 位）
篡改猴:5.0.0

**Comment by fishjar** [comment]
补丁设置那里添加一条规则：

![Screenshot from 2023-12-26 09-45-48](https://github.com/fishjar/kiss-rules/assets/1157624/88a8adc1-7cbd-46e5-bbda-df86eb1bfbf8)

**Comment by C1oudTree** [comment]
问题解决了,谢谢作者!

**Comment by C1oudTree** [comment]
在这个商店页面有一个更新公告,如何翻译更新公告?
https://store.steampowered.com/app/2088570
![image](https://github.com/fishjar/kiss-rules/assets/90253489/1b03a9a7-f8e3-4497-a92e-4181d5ff9cce)
![image](https://github.com/fishjar/kiss-rules/assets/90253489/40ae7124-035c-4085-81a5-814f100142cd)

**Comment by fishjar** [comment]
> 在这个商店页面有一个更新公告,如何翻译更新公告? https://store.steampowered.com/app/2088570

这个页面非常特殊，需要调整webfix相关的代码，下个版本更新后才能翻译。

补丁设置： 
```css
#game_area_description, #devnotes_expander, .FullModalOverlay .partnereventdisplay_EventDetailsBody_3v0cw
```
并且需要注意：必须先加载完页面内容后，再翻译，否则页面会出错。

**Comment by C1oudTree** [comment]
谢谢老哥，先加载完页面内容后，再翻译，有些麻烦，我还是等下一个版本吧

**Comment by fishjar** [comment]
> 谢谢老哥，先加载完页面内容后，再翻译，有些麻烦，我还是等下一个版本吧

就是说下个版本需要这么做，目前版本完全不能翻译。
因为这种属于极特殊的页面，不想花太多时间去研究。

**Comment by C1oudTree** [comment]
> 就是说下个版本需要这么做，目前版本完全不能翻译。
> 因为这种属于极特殊的页面，不想花太多时间去研究。

明白了
