### ISSUE TITLE
请教一下如何添加规则（选择器）

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-rules#2]
比如这个页面：https://github.com/acmesh-official/acme.sh/wiki/Options-and-Params
我现在想要把右侧的导航进行翻译，需要换行展示翻译结果，且翻译结果跟原文样式一致，应该如何写规则呢？

使用选择器 `.Truncate-text.text-bold.py-1`， 带了原文的样式，但是没换行： 
![image](https://github.com/fishjar/kiss-rules/assets/32786903/b4c6e721-5950-4d57-b926-89b880358e6c)

使用选择器 `.Box-row.px-2.py-2`，换行了，但是没带原文样式：
![image](https://github.com/fishjar/kiss-rules/assets/32786903/7f7a8977-7acb-49b1-8d33-25238e40f009)

有办法做到让翻译结果，既换行，又可以带原文样式吗？

**Comment by fishjar** [comment]
控制换行有两个方案：

1、最简单的就是在设置那里 `换行字符数` 改小一点

2、通过自定义样式控制，这个写法就很多

比如：

```css
display: block;
```

比如：

```css
&::before{
    content: "\a";
    white-space: pre;
}
```

**Comment by leic4u** [comment]
> 控制换行有两个方案：
> 1、最简单的就是在设置那里 换行字符数 改小一点
> 2、通过自定义样式控制，这个写法就很多

```display: block;```
这个写法确实有效，但是实测下来，如果样式用了背景色的话，会导致一整行都有颜色，不太友好。

```&::before{
    content: "\a";
    white-space: pre;
}```
这个写法也有用，但是会出现换两行的情况。

最后还是用最小换行字数调整为1解决了。。。
