### ISSUE TITLE
Google Play 规则求助

### ISSUE THREAD

**Issue by C1oudTree** [fishjar/kiss-rules#20]
我在这个网址使用自定义规则完全没有翻译,应该怎么翻译这个网页

https://play.google.com/store/apps/details?id=io.keybase.ossifrage

```json
  {
    "pattern": "play.google.com/store/apps/details",
    "selector": ":is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote);.bARER;.SfzRHd;.h3YV2d",
    "translator": "*",
    "fromLang": "auto",
    "toLang": "zh-CN",
    "textStyle": "*",
    "transOpen": "true",
    "bgColor": "",
    "textDiyStyle": "background: rgba(196, 196, 196, 0.2);\nPadding: 3px;\nborder-radius: 7px;\nline-height: 1.8;"
  }
```

**Comment by fishjar** [comment]
补丁设置那里加一条，翻译规则默认即可：

![Screenshot from 2023-12-28 11-20-43](https://github.com/fishjar/kiss-rules/assets/1157624/7b99e1bc-64f6-41d2-b317-f4b51f6f6de7)

![Screenshot from 2023-12-28 11-23-44](https://github.com/fishjar/kiss-rules/assets/1157624/ff223759-6332-4542-8cdf-f4ec59113d5b)

**Comment by C1oudTree** [comment]
谢谢作者,我现在觉得是其他问题,好像所有chrome浏览器上的油猴插件都无法在这个网页起效
