### ISSUE TITLE
能否把登录账号的相关信息从翻译输入中排除掉？

### ISSUE THREAD

**Issue by showgood163** [fishjar/kiss-rules#22]
原因：针对个人隐私的更优保护。

复现：打开reddit，登录之后页面上会有用户信息，开启翻译之后和用户名相关的字段都会被翻译。

**Comment by fishjar** [comment]
不知需要排除的信息是否被元素包裹，如果是的话，刚好最新版的规则设置增加了一个`保留元素选择器`，填上就可以排除了，不会发送到远端服务器。

**Comment by showgood163** [comment]
CSS选择器什么的，我补一下知识，再试试看
