### ISSUE TITLE
chromereleases.googleblog.com 规则求助

### ISSUE THREAD

**Issue by Bush2021** [fishjar/kiss-rules#24]
大部分情况下，`webfix br` 选择 `div[class^=post]`，规则用默认，效果是正常的；

但是有些用 `span` 包裹的文字无法正确翻译，如 https://chromereleases.googleblog.com/2024/01/stable-channel-update-for-desktop.html ；

请问能否支持？

**Comment by fishjar** [comment]
参考：
![Screenshot from 2024-01-08 11-09-55](https://github.com/fishjar/kiss-rules/assets/1157624/62f5f67e-974b-4d5b-b8fd-90ece86d114f)

**Comment by Bush2021** [comment]
谢谢，这个解决了大部分情况，但还有些页面会无法换行，如 https://chromereleases.googleblog.com/2023/12/stable-channel-update-for-desktop_20.html , https://chromereleases.googleblog.com/2023/11/stable-channel-update-for.html ；

是不是这个网站本身写的比较混乱？

**Comment by fishjar** [comment]
这个网站页面元素随意嵌套，很难完美翻译。建议用划词翻译功能辅助阅读。

**Comment by Bush2021** [comment]
好的，感谢解答~
