### ISSUE TITLE
Telegram WebK 规则求助

### ISSUE THREAD

**Issue by Bush2021** [fishjar/kiss-rules#27]
TG WebK 现有规则无法正确逐行翻译，由于网站使用 `\n` 换行，所以我尝试使用 `webfix bn`，选择器是 `.message`；

这样写可以正常翻译，但是切换回原文之后 webfix 添加的空行会把文本纵间距撑开，请问是否有办法解决？

效果如图：

![2024-01-10_155852](https://github.com/fishjar/kiss-rules/assets/79072750/7bd5ba30-a830-478d-a7b0-f4f7896ff3c3)
![2024-01-10_155908](https://github.com/fishjar/kiss-rules/assets/79072750/0da61abb-770f-4f04-982d-5f167d8973e5)

**Comment by Bush2021** [comment]
> 可能是`bn` 修复函数换为`<p>`元素后行间距变大了，可以试试`bnToDiv`修复函数，不过翻译规则要添加`div.kiss-p`

谢谢，这个修复函数有效；

还有个小问题，使用这个修复函数，帖子下的表情（`reactions-element`）反应会多出来一行，貌似是因为 `webfix` 不能设置排除元素，不知道是否打算支持呢？

**Comment by Bush2021** [comment]
规则保留元素写了 `div[class^=time], .peer-title, .document-wrapper, .message.spoilers-container custom-emoji-element, reactions-element`，所以不会造成这部分翻译内容错误，就只会多出一行，如图：

![image](https://github.com/fishjar/kiss-rules/assets/79072750/ddc9e0e0-7031-4895-a751-40db8d55ba6e)

**Comment by fishjar** [comment]
我看了下，怎么我看到是`<br>`换行的，然后如下设置就可以了：

![Screenshot from 2024-01-11 10-36-36](https://github.com/fishjar/kiss-rules/assets/1157624/915badc5-8f01-4dee-9f8f-f77c50359cf5)

![Screenshot from 2024-01-11 10-37-07](https://github.com/fishjar/kiss-rules/assets/1157624/83dc094e-4f2d-46f5-8f74-05b4f5ecb698)

![Screenshot from 2024-01-11 10-37-51](https://github.com/fishjar/kiss-rules/assets/1157624/909ca2bb-a23f-4c86-94ae-3a64a73f0d9a)

**Comment by Bush2021** [comment]
可能你用的是 WebA，WebK 页面设计不一样？

On Jan 10, 2024, at 9:38 PM, Gabe ***@***.***> wrote:

﻿

我看了下，怎么我看到是<br>换行的，然后如下设置就可以了：

Screenshot.from.2024-01-11.10-36-36.png (view on web)<https://github.com/fishjar/kiss-rules/assets/1157624/915badc5-8f01-4dee-9f8f-f77c50359cf5>

Screenshot.from.2024-01-11.10-37-07.png (view on web)<https://github.com/fishjar/kiss-rules/assets/1157624/83dc094e-4f2d-46f5-8f74-05b4f5ecb698>

Screenshot.from.2024-01-11.10-37-51.png (view on web)<https://github.com/fishjar/kiss-rules/assets/1157624/909ca2bb-a23f-4c86-94ae-3a64a73f0d9a>

**Comment by Bush2021** [comment]
﻿
可能你用的是 WebA，WebK 页面设计不一样？

On Jan 10, 2024, at 9:38 PM, Gabe ***@***.***> wrote:

﻿

我看了下，怎么我看到是<br>换行的，然后如下设置就可以了：

Screenshot.from.2024-01-11.10-36-36.png (view on web)<https://github.com/fishjar/kiss-rules/assets/1157624/915badc5-8f01-4dee-9f8f-f77c50359cf5>

Screenshot.from.2024-01-11.10-37-07.png (view on web)<https://github.com/fishjar/kiss-rules/assets/1157624/83dc094e-4f2d-46f5-8f74-05b4f5ecb698>

Screenshot.from.2024-01-11.10-37-51.png (view on web)<https://github.com/fishjar/kiss-rules/assets/1157624/909ca2bb-a23f-4c86-94ae-3a64a73f0d9a>

**Comment by Bush2021** [comment]
可能你用的是 WebA，WebK 页面设计不一样？

**Comment by fishjar** [comment]
> 可能你用的是 WebA，WebK 页面设计不一样？

对。

webK存在你说的问题。`reactions-element`被包裹后，会重新自动添加一个新的，所以看到了两个。

暂时没想到简单的好办法，不影响阅读就先这样吧。

**Comment by fishjar** [comment]
或者用webA，页面结构不一样，但内容一样

**Comment by Bush2021** [comment]
> 对。
> 
> webK存在你说的问题。`reactions-element`被包裹后，会重新自动添加一个新的，所以看到了两个。
> 
> 暂时没想到简单的好办法，不影响阅读就先这样吧。

好的，我 pr 了。
