### ISSUE TITLE
Hacker News 规则问题

### ISSUE THREAD

**Issue by ilupin** [fishjar/kiss-rules#29]
测试网址：https://news.ycombinator.com/item?id=39012544

在默认规则 `.title, .commtext` 下，翻译后的评论内容不会分段，另外标题下的描述没有翻译。
改成 `.title, .toptext p, .commtext p` 后，可以从第二段开始逐段翻译，但翻译不了第一段，因为不在 `<p>` 里面。

**Comment by fishjar** [comment]
`补丁设置`和`规则设置`，如图即可：

![Screenshot from 2024-01-18 17-16-06](https://github.com/fishjar/kiss-rules/assets/1157624/588569d4-3b62-444e-9e2e-7dc82db126ba)

![Screenshot from 2024-01-18 17-16-38](https://github.com/fishjar/kiss-rules/assets/1157624/64c3b267-f342-43df-ba5a-9221af281426)

![Screenshot from 2024-01-18 17-17-17](https://github.com/fishjar/kiss-rules/assets/1157624/74675c60-1fdf-4a0a-bf7a-7e6a5029b84d)

**Comment by ilupin** [comment]
谢谢！完全解决了之前的两个问题，我认为可以作为 Hacker News 的默认设置了
