### ISSUE TITLE
弹窗翻译字数限制

### ISSUE THREAD

**Issue by Wesdurant** [fishjar/kiss-rules#30]
你还，请问这个弹窗之后的翻译就是有字数限制的吗？还是我的设置问题？我用的是chatGPT的api接口。

若能解答，不胜感激！

![QQ截图20240118145258](https://github.com/fishjar/kiss-rules/assets/156995526/94b17cfb-837a-4b55-aa44-0b1468141191)

**Comment by fishjar** [comment]
弹窗翻译没有限制字数，有可能是翻译接口只返回了这么多。

也有可能返回多条数据，我只处理了第一条，因为没有接口测试，不能确定。

**Comment by Wesdurant** [comment]
感谢解答。你说的这种情况，我这边能通过设置解决么？

**Comment by fishjar** [comment]
可以打开开发者调试页面看接口返回数据来确定是什么原因。

也可以等下个版本我会聚合多条数据，到时候再试试。

**Comment by Wesdurant** [comment]
好的，感谢
