### ISSUE TITLE
Researchgate页面翻译不全

### ISSUE THREAD

**Issue by zousiyu1995** [fishjar/kiss-rules#32]
如图所示，论文标题没有翻译，请问作者能否添加对应规则。感谢！

测试页面：https://www.researchgate.net/profile/David-Hu-13/research

![image](https://github.com/fishjar/kiss-rules/assets/7608449/83ca2354-31d0-4b6c-b835-e66c08c324f7)

**Comment by fishjar** [comment]
供参考：

```css
.nova-legacy-e-link, .nova-legacy-e-text, .nova-legacy-e-badge
```

![Screenshot from 2024-02-03 10-21-36](https://github.com/fishjar/kiss-rules/assets/1157624/6dd6d1d0-4360-4c3b-ad6c-147c0b99e862)
