### ISSUE TITLE
建议添加jointjs的规则&规则选择失败的问题

### ISSUE THREAD

**Issue by KazeLiu** [fishjar/kiss-rules#36]
这是我设置的规则。
``` json
{
    "pattern": "*.jointjs.com/*",
    "selector": ":is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote,td,tr)",
    "keepSelector": "code, img, svg,.docs-nav-items *",
    "terms": "",
    "translator": "Microsoft",
    "fromLang": "auto",
    "toLang": "zh-CN",
    "textStyle": "style_none",
    "transOpen": "true",
    "bgColor": "",
    "textDiyStyle": ""
  }
```
但是有个问题，我不知道怎么处理
![image](https://github.com/fishjar/kiss-rules/assets/22094581/dddc581e-d88d-44dd-914e-a891d56c9554)
我在selector里面写了td，但是这个处于td下面的内容没有被翻译（大部分都被翻译了），怀疑是这个td里面的文字包含了其他的标签导致不翻译，我不知道这个规则如何写。
html贴在下面了
``` html
<td>
            Callback function that is expected to return an array of minimal constraint points (in the form: <code class="highlighted"><span class="token punctuation">{</span> <span class="token literal-property property">x</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">y</span><span class="token operator">:</span> number <span class="token punctuation">}</span></code>), relative to the paper.
            Minimal constraint points are points that should always be kept <b>inside</b> selected lane when resizing.
            If this option is left undefined, the default <code class="highlighted">minSizeConstraints</code> function is used instead
            which creates those points automatically from embedded shapes.
            Callback is called each time a handle starts to be dragged, the arguments passed are:
            <br>
            <br>
            <table>
                <tbody><tr style="-webkit-line-clamp: unset; max-height: none; height: auto;">
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;">model<kiss-translator style="visibility: visible;"> <span>型</span></kiss-translator></td>
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;"><i>dia.Element</i><kiss-translator style="visibility: visible;"> <span>日。元素</span></kiss-translator></td>
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;">Pool shape that the tool was added to.<kiss-translator style="visibility: visible;"><br><span>将工具添加到的池形状。</span></kiss-translator></td>
                </tr>
                <tr style="-webkit-line-clamp: unset; max-height: none; height: auto;">
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;">laneId<kiss-translator style="visibility: visible;"> <span>通道 ID</span></kiss-translator></td>
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;"><i>string</i><kiss-translator style="visibility: visible;"> <span>字符串</span></kiss-translator></td>
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;">Id of the lane that the tool was initialized with.<kiss-translator style="visibility: visible;"><br><span>初始化工具时使用的通道的 ID。</span></kiss-translator></td>
                </tr>
                <tr style="-webkit-line-clamp: unset; max-height: none; height: auto;">
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;">handleSide<kiss-translator style="visibility: visible;"> <span>handleSide（手柄侧）</span></kiss-translator></td>
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;"><i>"left" | "top" | "right" | "bottom"</i><kiss-translator style="visibility: visible;"><br><span>“左” |“顶部” |“对” |“底部”</span></kiss-translator></td>
                    <td style="-webkit-line-clamp: unset; max-height: none; height: auto;">Position of the dragged handle (relative to the lane).<kiss-translator style="visibility: visible;"><br><span>拖动手柄的位置（相对于车道）。</span></kiss-translator></td>
                </tr>
            </tbody></table>
        </td>
```

**Comment by fishjar** [comment]
原因是`td`里面嵌套了`td`，只会翻译最里层的。

这种情况，我建议用划词翻译临时解决比较简单。

当然，你这个例子也可以加个`br`的`webfix`来解决。

**Comment by KazeLiu** [comment]
> 原因是`td`里面嵌套了`td`，只会翻译最里层的。
> 
> 这种情况，我建议用划词翻译临时解决比较简单。
> 
> 当然，你这个例子也可以加个`br`的`webfix`来解决。

不好意思，我没有理解您的意思，我不知道你说的加个``br``是啥意思，它应该怎么加？
能否直接把选择器的代码交给我。
这个测试页面的网址是 https://resources.jointjs.com/docs/rappid/v4.0/elementTools.SwimlaneTransform.html

**Comment by fishjar** [comment]
参考设置：

![Screenshot from 2024-03-05 14-52-17](https://github.com/fishjar/kiss-rules/assets/1157624/a98e3df8-9295-488e-b227-66234da97cb8)

![Screenshot from 2024-03-05 14-52-36](https://github.com/fishjar/kiss-rules/assets/1157624/40a47d52-0fc9-4d54-914c-3169f35eeed7)

效果：

![Screenshot from 2024-03-05 14-52-53](https://github.com/fishjar/kiss-rules/assets/1157624/db8f22a4-ea7f-4609-b352-bc08a2583ebd)

**Comment by KazeLiu** [comment]
> 参考设置：
> 
> ![Screenshot from 2024-03-05 14-52-17](https://private-user-images.githubusercontent.com/1157624/310012530-a98e3df8-9295-488e-b227-66234da97cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjE5ODIsIm5iZiI6MTcwOTYyMTY4MiwicGF0aCI6Ii8xMTU3NjI0LzMxMDAxMjUzMC1hOThlM2RmOC05Mjk1LTQ4OGUtYjIyNy02NjIzNGRhOTdjYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDY1NDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU2NTRlN2JjNTQwZTRmMGY3ZjJmNTIyNmJmMzdmZmUxOTFiMzIyNTkyZjljZmY1ZDI5MzE1ZGYyMzRjMzQwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o3WvuRM3wAWgD2RmUjKWnYWX9ubssnNmCWvEssl5wZQ)
> 
> ![Screenshot from 2024-03-05 14-52-36](https://private-user-images.githubusercontent.com/1157624/310012557-40a47d52-0fc9-4d54-914c-3169f35eeed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjE5ODIsIm5iZiI6MTcwOTYyMTY4MiwicGF0aCI6Ii8xMTU3NjI0LzMxMDAxMjU1Ny00MGE0N2Q1Mi0wZmM5LTRkNTQtOTE0Yy0zMTY5ZjM1ZWVlZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDY1NDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk1YzY0OTM5ZmI2ZDVjYzQwY2ZjZDAxM2MxODlhOWRhYzBhODFkZWVmZjllM2VmY2I5OGE5MjcyOGRkMzAzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D9Ort-IySe17_gnGkMiF4H42Z_oWoETeuGwSAHPz_K0)
> 
> 效果：
> 
> ![Screenshot from 2024-03-05 14-52-53](https://private-user-images.githubusercontent.com/1157624/310012626-db8f22a4-ea7f-4609-b352-bc08a2583ebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjE5ODIsIm5iZiI6MTcwOTYyMTY4MiwicGF0aCI6Ii8xMTU3NjI0LzMxMDAxMjYyNi1kYjhmMjJhNC1lYTdmLTQ2MDktYjM1Mi1iYzA4YTI1ODNlYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDY1NDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVmNmIyNDkxYjU3NWJlODE3YWRhNjJlZmMzMWY5YjQ3YTIyOWE2OTY1NWVkYWQxYmY4ZGZjYmVmYjY4NzBhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bxj3vWb3iTiSxZTt0JSL3nHo-YlGk0d-CG_HMhJD7Ok)

谢谢
