### ISSUE TITLE
element.io 规则求助

### ISSUE THREAD

**Issue by KyoSakuyo** [fishjar/kiss-rules#37]
![image](https://github.com/fishjar/kiss-rules/assets/59904064/06747ae5-4957-44d2-9589-fb518dacd3bc)

在matrix实例element.io的消息列表中，如果消息中含有对上一条信息的引用，则该条消息的正文无法被翻译（只有引用的部分被翻译）。

**Comment by fishjar** [comment]
看不到页面代码，不过猜测类似这个issue： https://github.com/fishjar/kiss-translator/issues/88

包含下面这样的代码，需要配置一个webfix来解决。

```html
<div class="div">
  <blockquote>text</blockquote>
  text
</div>
```
