### ISSUE TITLE
规则求助：https://app.immersivetranslate.com/pdf/

### ISSUE THREAD

**Issue by KyoSakuyo** [fishjar/kiss-rules#38]
这是竞品沉浸式翻译的pdf viewer，左边是PDF源文件，右边是转换后的富文本，

沉浸式翻译作用于此页面时，只翻译右边，忽略左边。
kiss translator对此页面无翻译。
![image](https://github.com/fishjar/kiss-rules/assets/59904064/ee036d27-0f5c-425f-9bab-0ce7a97887a5)

**Comment by fishjar** [comment]
实际是有翻译，只是样式问题，看不到翻译的文本

**Comment by fishjar** [comment]
新版本（v1.8.4）按如下配置即可：

![Screenshot from 2024-03-22 09-42-53](https://github.com/fishjar/kiss-rules/assets/1157624/53763e5e-cb41-4e3c-ba72-25e24f5b9265)
