### ISSUE TITLE
规则求助

### ISSUE THREAD

**Issue by Wei-Winter** [fishjar/kiss-rules#39]
https://orionfeedback.org/
此网站使用kiss翻译会破坏原网页布局，每个贴子的下面会有不同颜色的分类标签，kiss会把分类标签的颜色覆盖为黑色，如何在使用仅译文的情况下不会破坏原布局

**Comment by fishjar** [comment]
可以参考如下规则设置：

![Screenshot from 2024-05-15 11-25-07](https://github.com/fishjar/kiss-rules/assets/1157624/73b8b55f-3b29-4e43-a5bd-6f6754e3c6dc)

效果：

![Screenshot from 2024-05-15 11-26-11](https://github.com/fishjar/kiss-rules/assets/1157624/10f491fd-b082-4307-a036-f2648fe9282a)
