### ISSUE TITLE
Website parse: paulgraham.com

### ISSUE THREAD

**Issue by saccohuo** [fishjar/kiss-rules#44]
This website cannot translate correctly, please help me handle it.

https://paulgraham.com/persistence.html

**Comment by fishjar** [comment]
<img width="286" alt="11111" src="https://github.com/user-attachments/assets/9f0c7a16-9889-40ae-9d18-ba4434871216">

**Comment by saccohuo** [comment]
> <img alt="11111" width="286" src="https://private-user-images.githubusercontent.com/1157624/348893530-9f0c7a16-9889-40ae-9d18-ba4434871216.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDA4ODYsIm5iZiI6MTcyMTE0MDU4NiwicGF0aCI6Ii8xMTU3NjI0LzM0ODg5MzUzMC05ZjBjN2ExNi05ODg5LTQwYWUtOWQxOC1iYTQ0MzQ4NzEyMTYuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMTQzNjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc1YmVjOTU4YTAzMTllNjliN2M0MTMzMjc3OTk1YjdiMzlmZTczODBkMmU0OTBlMzBkNmJmN2RkZjhkYzFiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hMNT8DUoBtQG_VqSTuWkhEoOYWrjFZmlUY8PTiu4SWA">

Many thanks, it works.
