### ISSUE TITLE
请教如何实现部分论坛类网站的分段翻译

### ISSUE THREAD

**Issue by Bush2021** [fishjar/kiss-rules#5]
https://forum.ru-board.com/topic.cgi?forum=5&topic=51073#1

比如这个俄语论坛，我自定义的选择器是
`span.post, .tit, .dats`

但是实现的效果却是整段一起翻译了，视觉效果不太好，请教一下是否有办法解决呢？

**Comment by Bush2021** [comment]
嗯……似乎把 HTML 的 br 换行改成 p 可以，所以修改 webfixer 脚本就可以了？

**Comment by fishjar** [comment]
`webfix.js` 增加：
```js
  {
    pattern: "forum.ru-board.com",
    selector: "span.post",
    rootSelector: "",
    fixer: FIXER_BR,
  },
```

`rules.js` 增加：
```js
  "forum.ru-board.com": `.tit, .dats, span.post :is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote)`,
```
我已经更新了，在设置里面操作`同步规则`和`同步补丁`即可。

**Comment by fishjar** [comment]
效果：
![Screenshot from 2023-10-07 10-14-46](https://github.com/fishjar/kiss-rules/assets/1157624/b7e02c8f-bde1-47bc-985f-aede8499b3e4)

**Comment by Bush2021** [comment]
感谢指教，问题解决了！
