### ISSUE TITLE
blogs.windows.com

### ISSUE THREAD

**Issue by Bush2021** [fishjar/kiss-rules#7]
https://github.com/fishjar/kiss-rules/assets/79072750/1041f491-5268-4d7c-bb54-52fcb472d245

https://blogs.windows.com/windows-insider/2023/09/26/releasing-windows-11-version-23h2-to-the-release-preview-channel/

如图，红框内容翻译不正常，请求支持。规则如下：
`:is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote), .c-uhf-nav-link, figcaption`

**Comment by fishjar** [comment]
1、第一个红矿，原因是浏览器语言识别的bug，误将`Windows Experience`识别为中文了，所以没有翻译。
![Screenshot from 2023-10-09 14-40-01](https://github.com/fishjar/kiss-rules/assets/1157624/58955e5e-07ec-4fb2-8767-f423f7047b2f)


2、第二个红框，这里需要增加一条`webfix`规则。

```js
    {
      pattern: "blogs.windows.com",
      selector: ".t-content>div>ul>li",
      rootSelector: "",
      fixer: FIXER_BR,
    },
```

效果：
![Screenshot from 2023-10-09 14-40-58](https://github.com/fishjar/kiss-rules/assets/1157624/ad74de57-d96c-4d89-bddb-cb509d5f02ce)

**Comment by fishjar** [comment]
如果css选择器选择不到的文本，一般都可以用这个方法解决
